### ISSUE TITLE
Object(...) is not a function issue occur 

### ISSUE THREAD

**Issue by Yash5472** [aakashbansal/Beep-chat-app-Ionic-app#1]

**Comment by aakashbansal** [comment]
Hey @Yash5472 ! Could you please elaborate on the issue so that I might be able to help you better?

**Comment by Yash5472** [comment]
Hello sir!!... Actually, I could not find an actual issue but it, again and again, showing error like 
TypeError: Cannot read property 'Observable' of undefined
    at MergeMapSubscriber.project (http://localhost:8100/build/main.js:357:68)
    at MergeMapSubscriber._tryNext (http://localhost:8100/build/vendor.js:40687:27)
    at MergeMapSubscriber._next (http://localhost:8100/build/vendor.js:40677:18)
    at MergeMapSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:18247:18)
    at MergeMapSubscriber.notifyNext (http://localhost:8100/build/vendor.js:40710:26)
    at InnerSubscriber._next (http://localhost:8100/build/vendor.js:32314:21)
    at InnerSubscriber.Subscriber.next (http://localhost:8100/build/vendor.js:18247:18)
    at http://localhost:8100/build/vendor.js:125878:112
    at t.invoke (http://localhost:8100/build/polyfills.js:3:14976)
    at Object.onInvoke (http://localhost:8100/build/vendor.js:5150:33)

**Comment by Yash5472** [comment]
First error would be like,
**Typescript Error
Module '"/home/yash/Desktop/ionic-project/udemy_course/Beep-chat-app-Ionic-app-master/node_modules/firebase/index"' has no exported member 'functions'.**
Location:**### node_modules/@angular/fire/firebase.app.module.d.ts**
and then second error is like:
**Typescript Error
Property 'key' does not exist on type '{}'.**
location:**### src/providers/chat-service/chat-service.ts**
help sir.. need it

**Comment by aakashbansal** [comment]
This looks like a dependency issue. You might not have installed all the dependencies. It seems as if Firebase is not properly set up and more specifically, Google Cloud Functions are not properly set up. Go through the project README thoroughly. All steps are properly mentioned. 
Check this : https://firebase.google.com/docs/web/setup.

If the issue still persists, do let me know.
Cheers!

**Comment by Yash5472** [comment]
Typescript Error
Property 'key' does not exist on type '{}'. 
Location:**src/providers/chat-service/chat-service.ts**

```
getLastMessages(): Observable<Message[]> {
        return this.auth.getAuthenticatedUser()
            .map(user => user.uid)
            .mergeMap(userId => this.database.list(`/last-messages/${userId}`)
                .snapshotChanges())
            .mergeMap(lastMessages =>
                Observable.forkJoin(
                    lastMessages.map(eachMessage =>
                       `this.database.object<Message>(`/messages/${eachMessage.payload.val().key}`).valueChanges().first()),`
                    (...vals) => {
                        return vals;
                    })
            )
    }
```
How to solve this one. i tried everything but nothing can solve it ... need help sir!!!

**Comment by Yash5472** [comment]
Typescript Error
Module '"/home/yash/Desktop/ionic-project/udemy_course/Beep-chat-app-Ionic-app/node_modules/firebase/index"' has no exported member 'functions'.
location: node_modules/@angular/fire/firebase.app.module.d.ts
```
import { InjectionToken } from '@angular/core';
import { app, auth, database, firestore, functions, messaging, storage } from 'firebase/app';
export declare type FirebaseOptions = {

```
after following every step properly, still, I found this error ... I tried for thrice but it wasn't working anymore. How do I solve it?

**Comment by aakashbansal** [comment]
Its been almost a year since I last worked with the project. There were many similar types of errors I faced that you are seeing now. I don't exactly remember how I solved each one. So, I can only tell you to check these things : 
1. Did you clone the project as it is or made any changes, even the tiniest ?
2. Did you publish the Database rules from src/config/firebase.database.rules.txt following all the steps ?
3. Did you set up firebase functions and even **deployed** (Please check for deployment on Firebase console) them ?

If you followed all these steps along with the ones mentioned in README and still face the error, it might be entirely possible that Firebase may have made breaking changes in their API. I'm saying this because the code which is given in the udemy course did not work when I tried  as there were changes in Firebase API that rendered it useless. So, I had to refer docs and make required changes. 
I suggest you do the same.

**Comment by Yash5472** [comment]
Hello sir, I had solved that error by own ... thank you for your support... good day

**Comment by aakashbansal** [comment]
Awesome! What was the issue then ?

**Comment by Yash5472** [comment]
We need to use npm install angularfire2@5.0.0-rc.6 firebase@4.12.1
it will solve the issue.

**Comment by aakashbansal** [comment]
Okay. So it was a dependency issue.
Current version is using angularfire2@5.0.0-rc.5-next.

Thanks for pointing this out. :)

I am closing this issue now.
